# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
#- set -o pipefail && xcodebuild test -workspace Example/vantiq-sdk-ios.xcworkspace -scheme vantiq-sdk-ios-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -workspace Example/vantiq-sdk-ios.xcworkspace -scheme vantiq-sdk-ios-Example -sdk iphonesimulator build test > build.log
- tail -n 100 build.log
- pod lib lint
